service:
  name: what
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  profile: starport

functions:
  register:
    handler: src/handler.rentalRegister
    events:
      - http:
          method: post
          path: starport/v1/rental