service:
  name: starport
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  profile: ajungweb-development
  region: us-west-2
  stage: dev

functions:
  rentalregister:
    handler: src/handler.rentalRegister
    events:
      - http:
          method: post
          path: starport/v1/rental
          cors: true
  telecomregister:
    handler: src/handler.telecomRegister
    events:
      - http:
          method: post
          path: starport/v1/telecom
          cors: true
  